refactor: add resize
Co-authored-by: Marjus Cako <marios.cako@gmail.com>
Co-authored-by: Ethereal-O <m15635418665@163.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -2,17 +2,20 @@
 
 FROM alpine
 
-ARG TARGETPLATFORM
-RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ] && [ "$TARGETPLATFORM" != "linux/arm/v7" ] && [ "$TARGETPLATFORM" != "linux/ppc64le" ] && [ "$TARGETPLATFORM" != "linux/riscv64" ]; then \
-    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
-    exit 1; \
-    fi
+# ARG TARGETPLATFORM
+# RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ] && [ "$TARGETPLATFORM" != "linux/arm/v7" ] && [ "$TARGETPLATFORM" != "linux/ppc64le" ] && [ "$TARGETPLATFORM" != "linux/riscv64" ]; then \
+#     echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+#     exit 1; \
+#     fi
 
-ENV ARCH ${TARGETPLATFORM#linux/}
-ENV ARCH ${ARCH%/v7}
+# ENV ARCH ${TARGETPLATFORM#linux/}
+# ENV ARCH ${ARCH%/v7}
 
 RUN apk update
 RUN apk upgrade --no-cache busybox zlib
 
-COPY bin/local-path-provisioner-${ARCH} /usr/bin/local-path-provisioner
+# COPY bin/local-path-provisioner-${ARCH} /usr/bin/local-path-provisioner
+COPY bin/local-path-provisioner-amd64 /usr/bin/local-path-provisioner
+# RUN ls /usr/bin/
+RUN ls /usr/bin
 CMD ["local-path-provisioner"]
