ci: migrating from Drone to github Actions
Signed-off-by: James Lu <james.lu@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,7 +1,17 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM alpine
+
+ARG TARGETPLATFORM
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH ${TARGETPLATFORM#linux/}
 
 RUN apk update
 RUN apk upgrade --no-cache busybox zlib
 
-COPY bin/local-path-provisioner /usr/bin/
+COPY bin/local-path-provisioner-${ARCH} /usr/bin/local-path-provisioner
 CMD ["local-path-provisioner"]
